# Generated by Django 6.0.4 on 2026-04-21 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(max_length=20)),
                ('venue_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('food_description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('available_until', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=100)),
                ('requester_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyFoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('item_name', models.CharField(max_length=120)),
                ('item_slug', models.SlugField(editable=False, max_length=140)),
                ('prepared_quantity', models.PositiveIntegerField(default=0)),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('waste_quantity', models.PositiveIntegerField(default=0)),
                ('is_day_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_food_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date', 'item_slug'), name='unique_food_record_per_day')],
            },
        ),
        migrations.CreateModel(
            name='PredictionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('item_name', models.CharField(max_length=120)),
                ('recommended_quantity', models.PositiveIntegerField(default=0)),
                ('model_used', models.CharField(default='heuristic', max_length=50)),
                ('trained_samples', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['item_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry_date', 'item_name'), name='unique_prediction_per_day')],
            },
        ),
    ]
