# Generated by Django 6.0.4 on 2026-04-22 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrequest",
            name="food_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="item_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="preferred_pickup_time",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="requested_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="scheduled_pickup_time",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("scheduled", "Scheduled"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
